sudo: false
language: ruby
cache: bundler
branches:
  only:
    - gh-pages
    - /.*/
before_install:
  - "gem update --system"
  - "gem --version"
  - "gem install bundler -v '~> 2.0'"
  - "bundle --version"
script: 
  - "bundle exec jekyll build"
