gems:
  - jekyll-redirect-from
markdown: kramdown
collections:
  book:
    output: true
  qs:
    output: true
  tutorial_base:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

      
      
      
      
      
